### ISSUE TITLE
/whois does not work

### ISSUE THREAD

**Issue by yoosi** [mumixam/weechat-twitch#1]
Typing `/whois [nick]` while in channel does not return user info. 

The following was sent to the core WeeChat buffer:
`15:26 python: stdout/stderr: Traceback (most recent call last):
15:26 python: stdout/stderr:   File "/home/yoosi/.weechat/python/autoload/twitch.py", line 127, in channel_api
15:26 python: stdout/stderr:     pcolor, pformat, dcolor, ncolor, name, dcolor, ccolor, ul, rul, create)
15:26 python: stdout/stderr: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)
15:26 ! python: error in function "channel_api"`

Note: All other Twitch commands appear to work.

I am running WeeChat 1.8

**Comment by mumixam** [comment]
Does it fail for any nick you try? based on the error im guessing the user your checking has a display nick that's using utf8. are you able to ```/whois justin```

**Comment by mumixam** [comment]
ok, i pushed some changes to a new branch testing. everything looks good in initial tests. please give it a try and leave feedback
https://github.com/mumixam/weechat-twitch/tree/testing
