### ISSUE TITLE
Allow token to be stored securely

### ISSUE THREAD

**Issue by jloh** [mumixam/weechat-twitch#10]
I love this extension and use it a lot. It would be fantastic if the oAuth token could be stored inside the [secure data storage](https://weechat.org/files/doc/stable/weechat_user.en.html#secured_data) feature.

**Comment by mumixam** [comment]
try with the latest commit. https://github.com/mumixam/weechat-twitch/commit/b9ab44d3fbd263bf0e7b4cfafba3e8ce5339d6dd

How to use:
```
/secure set twitchtoken "My.Token"
/set plugins.var.python.twitch.token ${sec.data.twitchtoken}
```

**Comment by jloh** [comment]
Thanks! I can confirm this works perfectly.

**Comment by jloh** [comment]
Would be great to get a new version released so weechat.org picks the change up 👍
