### ISSUE TITLE
Is this still working and/or supported?

### ISSUE THREAD

**Issue by goproslowyo** [mumixam/weechat-twitch#12]
Setup with a fresh compilation of weechat 3.1 and the latest version of the script in github and I am unable to get the script to auth to the Twitch API despite the `client_id` and `token` being both set and equal values. Here's the error response from the API:

```shell
twitch.py: Error with twitch API (data key missing from json)
twitch.py: {"error":"Unauthorized","status":401,"message":"Client ID and OAuth token do not match"}
```

Here's a screenshot the the settings too:
![image](https://user-images.githubusercontent.com/68455785/117287344-171e1a00-ae1f-11eb-9f0f-18f6ea84712c.png)

EDIT: I have also tried regenerating new tokens to no avail.

**Comment by mumixam** [comment]
Yes it still works fine for me.

the client_id and the token are not the same.
The error messages means that you have to use the app's client_id that generated the oauth token (or that your token is invalid)
your token is the same thing used as the server password but with "oauth:" removed



you can use my token generator. here is the link https://mumixam.github.io/weechat_twitch/

**Comment by goproslowyo** [comment]
Appreciate the quick follow up. User error indeed and all if well. Did not find your credential generation tool the first time around :) Thanks!
