### ISSUE TITLE
Can't connect to twitch

### ISSUE THREAD

**Issue by blogdemoi** [mumixam/weechat-twitch#13]
Hello,
I try to use  weechat-twitch, but no success. I also did `/set plugins.var.python.twitch.ssl_verify off` but it doesb't change anythin, I still have these errors:

```
irc: connecting to server irc.twitch.tv/6667 (SSL)...
19:33 ⚠ irc: TLS handshake failed
19:33 ⚠ irc: error: An unexpected TLS packet was received.
19:33 ℹ  irc: reconnecting to server in 10 seconds
19:33 ℹ  irc: reconnecting to server...
19:33 ℹ  irc: connecting to server irc.twitch.tv/6667 (SSL)...
19:33 ⚠ irc: TLS handshake failed
19:33 ⚠ irc: error: An unexpected TLS packet was received.
19:33 ℹ  irc: reconnecting to server in 20 seconds
19:33 irc: auto-reconnection is cancelled

What can be wrong?

Thank you.
```

**Comment by mumixam** [comment]
the TLS verify option for for the script communicating with the API.

the connection to the twitch irc server needs to be ssl/tls off

``/set irc.server.twitch.ssl off``

**Comment by mumixam** [comment]
the TLS verify option for for the script communicating with the API.

the connection to the twitch irc server needs to be ssl/tls off if you are using port 6667 or on if you are using port 6697
you are trying to connect via 6667 with SSL enabled.

either
```/set irc.server.twitch.ssl off```

or change to port 6697

if your server name is not twitch adjust accordingly

**Comment by blogdemoi** [comment]
Thank you @mumixam , it is connecting now.
