### ISSUE TITLE
whois does not seem to work

### ISSUE THREAD

**Issue by trobotham** [mumixam/weechat-twitch#6]
The /whois command does not seem to work, I have tried to enable debugging as well as disable tls, there is simply no output, no errors, no traceback nothing, it does catch the whois command as it does not return a error that whois does not exist however, it does not return any data.

**Comment by mumixam** [comment]
Thanks for report.
fixed in https://github.com/mumixam/weechat-twitch/commit/2317b0ce29d9b780a9460e695d66b7da6cd158da
