### ISSUE TITLE
irc error WHISPER command received not translated as a PRIVMSG

### ISSUE THREAD

**Issue by H2L29** [mumixam/weechat-twitch#7]
twitch.py version 0.8
weechat version 2.5
messages in the twitch server buffer

irc : commande "WHISPER" non trouvée :
@badges=;color=#00FF7F;display-name=Botisimo;emotes=;message-id=12;thread-id=***;turbo=0;user-id=***;user-type= :botisimo!botisimo@botisimo.tmi.twitch.tv PRIVMSG *** :Kich: 287,435

**Comment by mumixam** [comment]
I confirm this issue and it seems to be related to hook type of 'in' vs 'in2'. not sure why its not working with 'in2' but I've reverted it back to 'in' in master

fixed in https://github.com/mumixam/weechat-twitch/commit/b10b2b8619a3a779add050ab2763729cde9bf2a4
